// remote/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";

import "./index.scss";
import Greeter from "./Greeter";
import Counter from "./Counter";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: remote</div>
    <Greeter />
    <Counter />
  </div>
);
ReactDOM.render(<App />, document.getElementById("app"));

// solid-remote/src/App.jsx
import { render } from "solid-js/web";

import "./index.scss";

const App = () => (
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: solid-remote</div>
    <div>Framework: solid-js</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
);

export default function SolidWrapper({ ref }) {
  render(App, ref);
}
