// solid-remote/src/App.jsx
import { render } from "solid-js/web";

import "./index.scss";

const App = () => (
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: solid-remote</div>
    <div>Framework: solid-js</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
);

export default function SolidWrapper({ ref }) {
  render(App, ref);
}

// host/src/App.jsx
import React, { useEffect, useRef } from "react";
import ReactDOM from "react-dom";
import Greeter from "remote/Greeter";
import Counter from "remote/VerySecretComponent";
import SolidApp from "solid_remote/SolidApp";
import "./index.scss";

const App = () => {
  const divRef = useRef(null);
  useEffect(() => {
    setTimeout(() => {
      SolidApp({ ref: document.getElementById("app") });
    }, 5000);
  }, []);
  return (
    <div className="mt-10 text-3xl mx-auto max-w-6xl">
      <div>Name: host</div>
      <Greeter />
      <Counter />
      <div ref={divRef}></div>
    </div>
  );
};
ReactDOM.render(<App />, document.getElementById("app"));
